# Generated by Django 3.0.2 on 2021-03-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210316_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='testapp.Category', verbose_name='Наименование категории'),
            preserve_default=False,
        ),
    ]
